// ============================================================
// RAWBY — Login Screen
// Theme-aware: gradient hero, form card, footer links
// ============================================================
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../constants/app_constants.dart';
import '../providers/user_session_provider.dart';
import '../providers/router_provider.dart';
import '../services/api_service.dart';
import '../services/storage_service.dart';
import '../theme/app_colors.dart';
import '../widgets/rawby_logo.dart';

class LoginScreen extends ConsumerStatefulWidget {
  const LoginScreen({super.key});

  @override
  ConsumerState<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends ConsumerState<LoginScreen> {
  final _usernameController = TextEditingController();
  final _passwordController = TextEditingController();
  final _formKey = GlobalKey<FormState>();

  bool _isLoading = false;
  bool _obscurePassword = true;
  String? _errorMessage;

  @override
  void dispose() {
    _usernameController.dispose();
    _passwordController.dispose();
    super.dispose();
  }

  Future<void> _login() async {
    if (!_formKey.currentState!.validate()) return;
    setState(() {
      _isLoading = true;
      _errorMessage = null;
    });

    try {
      final api = ref.read(apiServiceProvider);
      final result = await api.login(
        username: _usernameController.text.trim(),
        password: _passwordController.text,
      );

      final token = result['token'] as String?;
      if (token != null) {
        api.setAuthToken(token);
        ref.read(storageServiceProvider).setString(AppConstants.authTokenKey, token);
      }

      final user = result['user'] as Map<String, dynamic>? ?? result;
      ref.read(userSessionProvider.notifier).setUser(
            userId: user['id'] as String? ?? '',
            username: user['username'] as String? ?? '',
            displayName: user['displayName'] as String? ?? '',
            email: user['email'] as String? ?? '',
            role: (user['isAdmin'] == true) ? 'admin' : 'user',
          );

      if (mounted) context.go(Routes.home);
    } catch (e) {
      setState(() {
        _errorMessage = _parseError(e);
      });
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  String _parseError(Object e) {
    final msg = e.toString().toLowerCase();
    if (msg.contains('403') || msg.contains('email_not_verified') || msg.contains('verify')) {
      return 'Please verify your email before logging in. Check your inbox.';
    }
    if (msg.contains('401') || msg.contains('invalid') || msg.contains('wrong')) {
      return 'Invalid username or password.';
    }
    if (msg.contains('timeout') || msg.contains('timed out')) {
      return 'Server is waking up (free hosting sleeps when idle). Give it a few seconds and tap Log in again.';
    }
    if (msg.contains('network') || msg.contains('connection') || msg.contains('socket')) {
      return 'No connection. Check your internet.';
    }
    return 'Something went wrong. Please try again.';
  }

  void _showAboutDialog(BuildContext context) {
    final theme = Theme.of(context);
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: theme.colorScheme.surfaceContainerHighest,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        title: Row(
          children: [
            Icon(Icons.videocam_rounded, color: theme.colorScheme.primary, size: 22),
            const SizedBox(width: 10),
            Text(
              'What is RAWBY?',
              style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w700),
            ),
          ],
        ),
        content: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                'RAWBY is a weekly filmmaking challenge app designed to help aspiring and experienced creators build a consistent creative habit. '
                'Instead of waiting for inspiration to strike, RAWBY gives you structure, accountability, and a community to grow with.',
                style: theme.textTheme.bodySmall?.copyWith(height: 1.5),
              ),
              const SizedBox(height: 16),
              _dialogSection(theme, 'The Weekly Cycle',
                'Every week you receive a set of creative prompts — either generated by AI or written by you. '
                'Pick one, plan your shoot, film it, and submit before the deadline. After submission, your Instagram engagement '
                '(likes and views) is tracked for 7 days to calculate your final score.',
              ),
              const SizedBox(height: 16),
              _dialogSection(theme, 'How Scoring Works',
                '• Each prompt has a difficulty: Sequence, Short Story, or Story + Character\n'
                '• Higher difficulty = more base points\n'
                '• On-time submission earns a bonus; late gets a penalty\n'
                '• Instagram likes and views add engagement points\n'
                '• Your total score determines your rank on the leaderboard',
              ),
              const SizedBox(height: 16),
              _dialogSection(theme, 'Features',
                '• Weekly prompts — AI-generated or custom\n'
                '• Gear tracker — catalog your cameras and lenses\n'
                '• Idea Bank — save prompts for later\n'
                '• Workflow planner — structured weekly tasks\n'
                '• Leaderboard — compete with other creators\n'
                '• Rank progression — climb from Starter to Legend\n'
                '• Achievement system — unlock milestones as you grow\n'
                '• AI assistant (Aurora) — your creative filmmaking coach',
              ),
              const SizedBox(height: 16),
              _dialogSection(theme, 'Availability',
                'RAWBY is a web app — no download required. Install it as a home screen app on any device: iOS (Safari → Add to Home Screen), Android (Chrome → Install App), or use it in any browser.',
              ),
              const SizedBox(height: 16),
              Text(
                'Stop overthinking. Start creating. That is the RAWBY way.',
                style: theme.textTheme.bodySmall?.copyWith(fontStyle: FontStyle.italic),
              ),
            ],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(ctx).pop(),
            child: const Text('Got it'),
          ),
        ],
      ),
    );
  }

  void _showPrivacyDialog(BuildContext context) {
    final theme = Theme.of(context);
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: theme.colorScheme.surfaceContainerHighest,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        title: Text(
          'Privacy Policy & Terms',
          style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w700),
        ),
        content: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                'Last updated: May 2026',
                style: theme.textTheme.bodySmall?.copyWith(color: theme.colorScheme.onSurfaceVariant),
              ),
              const SizedBox(height: 12),
              _dialogSection(theme, '1. Data We Collect',
                '• Account info: username, display name, email\n'
                '• Project data: prompts, submissions, scores, history\n'
                '• Instagram URLs you voluntarily provide\n'
                '• Engagement metrics: likes and views from linked posts\n'
                '• Device tokens for push notifications\n'
                '• Gear data and preferences you choose to track',
              ),
              const SizedBox(height: 16),
              _dialogSection(theme, '2. How We Use Your Data',
                '• To operate the weekly challenge cycle and scoring\n'
                '• To display your profile and rank on the leaderboard\n'
                '• To send opt-in push notifications\n'
                '• To generate AI-powered prompts and coaching via Groq / Anthropic APIs\n'
                '• We do not sell, rent, or share your data with third parties\n'
                '• We do not use your data for advertising',
              ),
              const SizedBox(height: 16),
              _dialogSection(theme, '3. Data Storage & Security',
                '• Session data stored locally with Hive encrypted storage\n'
                '• Backend data on Render-hosted servers\n'
                '• API communication uses HTTPS encryption\n'
                '• Auth tokens stored locally, never exposed to other apps',
              ),
              const SizedBox(height: 16),
              _dialogSection(theme, '4. Terms of Use',
                '• All creative content you produce remains entirely yours\n'
                '• Do not abuse the platform or manipulate scoring\n'
                '• We may suspend accounts that violate community guidelines\n'
                '• Service is provided "as-is" without warranty',
              ),
              const SizedBox(height: 16),
              _dialogSection(theme, '5. Subscription',
                '• RAWBY may offer a paid tier for advanced features\n'
                '• Payments processed securely via Stripe\n'
                '• You can cancel your subscription at any time\n'
                '• Free tier features remain accessible after cancellation',
              ),
              const SizedBox(height: 16),
              _dialogSection(theme, '6. Contact',
                'Questions or data deletion requests: zaron.films@gmail.com or reach out through the Feedback Wall.',
              ),
            ],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(ctx).pop(),
            child: const Text('Close'),
          ),
        ],
      ),
    );
  }

  Widget _dialogSection(ThemeData theme, String title, String body) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          style: theme.textTheme.labelMedium?.copyWith(
            color: theme.colorScheme.primary,
            fontWeight: FontWeight.w600,
          ),
        ),
        const SizedBox(height: 6),
        Text(
          body,
          style: theme.textTheme.bodySmall?.copyWith(
            height: 1.6,
            color: theme.colorScheme.onSurfaceVariant,
          ),
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final primary = theme.colorScheme.primary;
    final size = MediaQuery.sizeOf(context);

    return Scaffold(
      backgroundColor: theme.colorScheme.surface,
      body: Stack(
        children: [
          // Subtle pine wash at the very top — minimalist, not a loud hero.
          Positioned(
            top: 0,
            left: 0,
            right: 0,
            height: size.height * 0.34,
            child: DecoratedBox(
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [
                    RawbyPalette.green600.withValues(alpha: 0.10),
                    theme.colorScheme.surface.withValues(alpha: 0),
                  ],
                ),
              ),
            ),
          ),
          SafeArea(
            child: SingleChildScrollView(
              padding: const EdgeInsets.symmetric(horizontal: 24),
              child: Column(
                children: [
                  const SizedBox(height: 88),
                  // Logo — pine wordmark block
                  const RawbyLogo(size: 64),
                  const SizedBox(height: 18),
                  Text(
                    'Create. Compete. Grow.',
                    style: theme.textTheme.bodySmall?.copyWith(
                      color: theme.colorScheme.onSurfaceVariant,
                      letterSpacing: 1.2,
                    ),
                  ),
                  const SizedBox(height: 52),

                  // Form card — minimalist: faint fill, hairline border.
                  Container(
                    padding: const EdgeInsets.all(24),
                    decoration: BoxDecoration(
                      color: theme.colorScheme.surfaceContainerHighest.withValues(alpha: 0.5),
                      borderRadius: BorderRadius.circular(20),
                      border: Border.all(
                        color: theme.colorScheme.outlineVariant.withValues(alpha: 0.6),
                      ),
                    ),
                    child: Form(
                      key: _formKey,
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'Welcome back',
                            style: theme.textTheme.titleMedium?.copyWith(
                              fontWeight: FontWeight.w700,
                            ),
                          ),
                          const SizedBox(height: 2),
                          Text(
                            'Sign in to continue',
                            style: theme.textTheme.bodySmall?.copyWith(
                              color: theme.colorScheme.onSurfaceVariant,
                            ),
                          ),
                          const SizedBox(height: 20),

                          _buildField(
                            context,
                            controller: _usernameController,
                            hint: 'Username',
                            textInputAction: TextInputAction.next,
                            validator: (v) =>
                                (v == null || v.trim().isEmpty) ? 'Enter your username' : null,
                          ),
                          const SizedBox(height: 12),

                          TextFormField(
                            controller: _passwordController,
                            obscureText: _obscurePassword,
                            style: TextStyle(
                              color: theme.colorScheme.onSurface,
                              fontSize: 15,
                            ),
                            decoration: InputDecoration(
                              hintText: 'Password',
                              hintStyle: TextStyle(
                                color: theme.colorScheme.onSurfaceVariant,
                              ),
                              filled: true,
                              fillColor: theme.colorScheme.surfaceContainerHigh,
                              border: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(10),
                                borderSide: BorderSide.none,
                              ),
                              focusedBorder: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(10),
                                borderSide: BorderSide(color: primary, width: 2),
                              ),
                              contentPadding: const EdgeInsets.symmetric(
                                horizontal: 16,
                                vertical: 14,
                              ),
                              suffixIcon: IconButton(
                                icon: Icon(
                                  _obscurePassword
                                      ? Icons.visibility_off_outlined
                                      : Icons.visibility_outlined,
                                  color: theme.colorScheme.onSurfaceVariant,
                                  size: 18,
                                ),
                                onPressed: () =>
                                    setState(() => _obscurePassword = !_obscurePassword),
                              ),
                            ),
                            textInputAction: TextInputAction.done,
                            onFieldSubmitted: (_) => _login(),
                            validator: (v) =>
                                (v == null || v.isEmpty) ? 'Enter your password' : null,
                          ),

                          if (_errorMessage != null) ...[
                            const SizedBox(height: 10),
                            Text(
                              _errorMessage!,
                              style: TextStyle(
                                color: theme.colorScheme.error,
                                fontSize: 13,
                              ),
                              textAlign: TextAlign.center,
                            ),
                          ],

                          const SizedBox(height: 20),

                          SizedBox(
                            width: double.infinity,
                            child: FilledButton(
                              onPressed: _isLoading ? null : _login,
                              style: FilledButton.styleFrom(
                                padding: const EdgeInsets.symmetric(vertical: 15),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(12),
                                ),
                              ),
                              child: _isLoading
                                  ? const SizedBox(
                                      height: 20,
                                      width: 20,
                                      child: CircularProgressIndicator(
                                        strokeWidth: 2,
                                        color: Colors.white,
                                      ),
                                    )
                                  : const Text(
                                      'Log in',
                                      style: TextStyle(
                                        fontSize: 16,
                                        fontWeight: FontWeight.w600,
                                      ),
                                    ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),

                  const SizedBox(height: 20),

                  TextButton(
                    onPressed: () => _showAboutDialog(context),
                    child: Text(
                      'What is RAWBY?',
                      style: TextStyle(
                        color: theme.colorScheme.onSurfaceVariant,
                        fontSize: 13,
                        decoration: TextDecoration.underline,
                        decorationColor: theme.colorScheme.onSurfaceVariant,
                      ),
                    ),
                  ),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Text(
                        'No account? ',
                        style: TextStyle(
                          color: theme.colorScheme.onSurfaceVariant,
                          fontSize: 13,
                        ),
                      ),
                      TextButton(
                        onPressed: () => context.go(Routes.register),
                        style: TextButton.styleFrom(
                          padding: EdgeInsets.zero,
                          minimumSize: Size.zero,
                          tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                        ),
                        child: Text(
                          'Create one',
                          style: TextStyle(
                            color: primary,
                            fontSize: 13,
                            fontWeight: FontWeight.w600,
                            decoration: TextDecoration.underline,
                            decorationColor: primary,
                          ),
                        ),
                      ),
                    ],
                  ),
                  TextButton(
                    onPressed: () => _showPrivacyDialog(context),
                    child: Text(
                      'Privacy Policy & Terms',
                      style: TextStyle(
                        color: theme.colorScheme.onSurfaceVariant,
                        fontSize: 12,
                        decoration: TextDecoration.underline,
                        decorationColor: theme.colorScheme.onSurfaceVariant,
                      ),
                    ),
                  ),
                  const SizedBox(height: 36),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildField(
    BuildContext context, {
    required TextEditingController controller,
    required String hint,
    TextInputType? keyboardType,
    TextInputAction? textInputAction,
    String? Function(String?)? validator,
  }) {
    final theme = Theme.of(context);
    return TextFormField(
      controller: controller,
      keyboardType: keyboardType,
      style: TextStyle(color: theme.colorScheme.onSurface, fontSize: 15),
      decoration: InputDecoration(
        hintText: hint,
        hintStyle: TextStyle(color: theme.colorScheme.onSurfaceVariant),
        filled: true,
        fillColor: theme.colorScheme.surfaceContainerHigh,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: BorderSide.none,
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: BorderSide(color: theme.colorScheme.primary, width: 2),
        ),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
      ),
      textInputAction: textInputAction,
      autocorrect: false,
      validator: validator,
    );
  }
}
